Update conversation.py (#423)
If someone uses !wait on the first move the bot would raise Backing off play_game(...) for 1s (TypeError: ping() missing 1 required positional argument: 'disconnect_in') because we didn't set the disconnect_in parameter.